### ISSUE TITLE
Document the CSS color filter generator technique for theming single color images

### ISSUE THREAD

**Issue by uncenter** [catppuccin/userstyles#1089]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

We [use this technique in various places](https://github.com/search?q=repo%3Acatppuccin%2Fuserstyles%20%22filter%3A%20%40%22&type=code) for simple. single color PNGs/non vector images. Quite useful for small things, but the color filters need to be generated every time and we don't even document this at the moment. I'm thinking we create a new filter palette that is like our hex palette but with filters. And this wouldn't be included in the template by default but could be added for the userstyles that need it.

**Comment by Papweer** [comment]
I make a full pallete for all the filters. It was make using a modified version of [this code](https://stackoverflow.com/a/43960991/21487143) and all the filters have a loss of under 0.2 (every filter gives exactly the color it should).
```less
@catppuccin-filters: {
  @latte-filters:     { @rosewater-filter: brightness(0) saturate(100%) invert(64%) sepia(30%) saturate(628%) hue-rotate(323deg) brightness(91%) contrast(88%); @flamingo-filter: brightness(0) saturate(100%) invert(70%) sepia(56%) saturate(3732%) hue-rotate(314deg) brightness(102%) contrast(73%); @pink-filter: brightness(0) saturate(100%) invert(62%) sepia(85%) saturate(922%) hue-rotate(281deg) brightness(99%) contrast(85%); @mauve-filter: brightness(0) saturate(100%) invert(24%) sepia(63%) saturate(3507%) hue-rotate(257deg) brightness(95%) contrast(96%); @red-filter: brightness(0) saturate(100%) invert(13%) sepia(87%) saturate(4867%) hue-rotate(340deg) brightness(89%) contrast(96%); @maroon-filter: brightness(0) saturate(100%) invert(46%) sepia(93%) saturate(5935%) hue-rotate(339deg) brightness(117%) contrast(80%); @peach-filter: brightness(0) saturate(100%) invert(36%) sepia(100%) saturate(1087%) hue-rotate(356deg) brightness(103%) contrast(99%); @yellow-filter: brightness(0) saturate(100%) invert(80%) sepia(38%) saturate(5950%) hue-rotate(351deg) brightness(93%) contrast(87%); @green-filter: brightness(0) saturate(100%) invert(60%) sepia(72%) saturate(4143%) hue-rotate(76deg) brightness(95%) contrast(66%); @teal-filter: brightness(0) saturate(100%) invert(46%) sepia(16%) saturate(2899%) hue-rotate(138deg) brightness(94%) contrast(82%); @sky-filter: brightness(0) saturate(100%) invert(53%) sepia(85%) saturate(3255%) hue-rotate(165deg) brightness(98%) contrast(97%)@sapphire-filter: brightness(0) saturate(100%) invert(50%) sepia(35%) saturate(1001%) hue-rotate(141deg) brightness(99%) contrast(83%); @blue-filter: brightness(0) saturate(100%) invert(29%) sepia(100%) saturate(1496%) hue-rotate(208deg) brightness(94%) contrast(106%); @lavender-filter: brightness(0) saturate(100%) invert(49%) sepia(39%) saturate(797%) hue-rotate(194deg) brightness(103%) contrast(98%); @text-filter: brightness(0) saturate(100%) invert(30%) sepia(7%) saturate(1749%) hue-rotate(196deg) brightness(93%) contrast(87%); @subtext1-filter: brightness(0) saturate(100%) invert(36%) sepia(12%) saturate(902%) hue-rotate(196deg) brightness(95%) contrast(83%); @subtext0-filter: brightness(0) saturate(100%) invert(48%) sepia(6%) saturate(1160%) hue-rotate(195deg) brightness(88%) contrast(88%); @overlay2-filter: brightness(0) saturate(100%) invert(58%) sepia(16%) saturate(377%) hue-rotate(195deg) brightness(84%) contrast(86%); @overlay1-filter: brightness(0) saturate(100%) invert(61%) sepia(18%) saturate(263%) hue-rotate(194deg) brightness(91%) contrast(87%); @overlay0-filter: brightness(0) saturate(100%) invert(72%) sepia(5%) saturate(684%) hue-rotate(191deg) brightness(88%) contrast(90%); @surface2-filter: brightness(0) saturate(100%) invert(84%) sepia(8%) saturate(346%) hue-rotate(189deg) brightness(82%) contrast(95%); @surface1-filter: brightness(0) saturate(100%) invert(89%) sepia(12%) saturate(209%) hue-rotate(187deg) brightness(87%) contrast(85%); @surface0-filter: brightness(0) saturate(100%) invert(94%) sepia(4%) saturate(609%) hue-rotate(188deg) brightness(98%) contrast(75%); @base-filter: brightness(0) saturate(100%) invert(99%) sepia(1%) saturate(2029%) hue-rotate(182deg) brightness(99%) contrast(94%); @mantle-filter: brightness(0) saturate(100%) invert(98%) sepia(15%) saturate(866%) hue-rotate(177deg) brightness(99%) contrast(88%); @crust-filter: brightness(0) saturate(100%) invert(96%) sepia(3%) saturate(682%) hue-rotate(186deg) brightness(96%) contrast(89%); };
  @frappe-filters:    { @rosewater-filter: brightness(0) saturate(100%) invert(84%) sepia(26%) saturate(190%) hue-rotate(321deg) brightness(101%) contrast(90%); @flamingo-filter: brightness(0) saturate(100%) invert(79%) sepia(18%) saturate(374%) hue-rotate(317deg) brightness(101%) contrast(89%); @pink-filter: brightness(0) saturate(100%) invert(80%) sepia(14%) saturate(910%) hue-rotate(280deg) brightness(102%) contrast(91%); @mauve-filter: brightness(0) saturate(100%) invert(67%) sepia(47%) saturate(321%) hue-rotate(231deg) brightness(95%) contrast(89%); @red-filter: brightness(0) saturate(100%) invert(53%) sepia(42%) saturate(1710%) hue-rotate(316deg) brightness(115%) contrast(80%); @maroon-filter: brightness(0) saturate(100%) invert(66%) sepia(14%) saturate(968%) hue-rotate(308deg) brightness(100%) contrast(95%); @peach-filter: brightness(0) saturate(100%) invert(72%) sepia(16%) saturate(1279%) hue-rotate(331deg) brightness(96%) contrast(95%); @yellow-filter: brightness(0) saturate(100%) invert(88%) sepia(9%) saturate(1416%) hue-rotate(348deg) brightness(94%) contrast(90%); @green-filter: brightness(0) saturate(100%) invert(82%) sepia(30%) saturate(408%) hue-rotate(51deg) brightness(91%) contrast(90%); @teal-filter: brightness(0) saturate(100%) invert(78%) sepia(14%) saturate(781%) hue-rotate(122deg) brightness(92%) contrast(90%); @sky-filter: brightness(0) saturate(100%) invert(89%) sepia(7%) saturate(1511%) hue-rotate(147deg) brightness(91%) contrast(87%); @sapphire-filter: brightness(0) saturate(100%) invert(83%) sepia(6%) saturate(2868%) hue-rotate(167deg) brightness(90%) contrast(91%); @blue-filter: brightness(0) saturate(100%) invert(66%) sepia(21%) saturate(829%) hue-rotate(185deg) brightness(99%) contrast(89%); @lavender-filter: brightness(0) saturate(100%) invert(65%) sepia(72%) saturate(158%) hue-rotate(201deg) brightness(103%) contrast(89%); @text-filter: brightness(0) saturate(100%) invert(73%) sepia(4%) saturate(1839%) hue-rotate(193deg) brightness(115%) contrast(92%); @subtext1-filter: brightness(0) saturate(100%) invert(80%) sepia(27%) saturate(301%) hue-rotate(191deg) brightness(92%) contrast(93%); @subtext0-filter: brightness(0) saturate(100%) invert(82%) sepia(7%) saturate(1177%) hue-rotate(192deg) brightness(86%) contrast(85%); @overlay2-filter: brightness(0) saturate(100%) invert(69%) sepia(21%) saturate(354%) hue-rotate(190deg) brightness(87%) contrast(90%); @overlay1-filter: brightness(0) saturate(100%) invert(55%) sepia(22%) saturate(356%) hue-rotate(189deg) brightness(96%) contrast(87%); @overlay0-filter: brightness(0) saturate(100%) invert(48%) sepia(10%) saturate(818%) hue-rotate(192deg) brightness(96%) contrast(93%); @surface2-filter: brightness(0) saturate(100%) invert(43%) sepia(9%) saturate(1012%) hue-rotate(191deg) brightness(91%) contrast(88%); @surface1-filter: brightness(0) saturate(100%) invert(35%) sepia(11%) saturate(808%) hue-rotate(190deg) brightness(92%) contrast(95%); @surface0-filter: brightness(0) saturate(100%) invert(22%) sepia(40%) saturate(360%) hue-rotate(192deg) brightness(94%) contrast(84%); @base-filter: brightness(0) saturate(100%) invert(13%) sepia(8%) saturate(2938%) hue-rotate(192deg) brightness(95%) contrast(78%); @mantle-filter: brightness(0) saturate(100%) invert(11%) sepia(4%) saturate(5405%) hue-rotate(194deg) brightness(101%) contrast(85%); @crust-filter: brightness(0) saturate(100%) invert(12%) sepia(8%) saturate(2209%) hue-rotate(192deg) brightness(89%) contrast(90%); };
  @macchiato-filters: { @rosewater-filter: brightness(0) saturate(100%) invert(82%) sepia(5%) saturate(1375%) hue-rotate(192deg) brightness(104%) contrast(92%); @flamingo-filter: brightness(0) saturate(100%) invert(84%) sepia(6%) saturate(1088%) hue-rotate(192deg) brightness(93%) contrast(90%); @pink-filter: brightness(0) saturate(100%) invert(83%) sepia(8%) saturate(889%) hue-rotate(192deg) brightness(83%) contrast(90%); @mauve-filter: brightness(0) saturate(100%) invert(65%) sepia(32%) saturate(255%) hue-rotate(191deg) brightness(92%) contrast(77%); @red-filter: brightness(0) saturate(100%) invert(58%) sepia(22%) saturate(346%) hue-rotate(190deg) brightness(88%) contrast(91%); @maroon-filter: brightness(0) saturate(100%) invert(48%) sepia(16%) saturate(546%) hue-rotate(193deg) brightness(91%) contrast(86%); @peach-filter: brightness(0) saturate(100%) invert(40%) sepia(10%) saturate(948%) hue-rotate(192deg) brightness(90%) contrast(91%); @yellow-filter: brightness(0) saturate(100%) invert(29%) sepia(9%) saturate(1486%) hue-rotate(194deg) brightness(92%) contrast(85%); @green-filter: brightness(0) saturate(100%) invert(17%) sepia(5%) saturate(4899%) hue-rotate(193deg) brightness(91%) contrast(78%); @teal-filter: brightness(0) saturate(100%) invert(6%) sepia(55%) saturate(1381%) hue-rotate(207deg) brightness(99%) contrast(80%); @sky-filter: brightness(0) saturate(100%) invert(8%) sepia(6%) saturate(5273%) hue-rotate(196deg) brightness(96%) contrast(87%); @sapphire-filter: brightness(0) saturate(100%) invert(6%) sepia(7%) saturate(4524%) hue-rotate(198deg) brightness(98%) contrast(90%); @blue-filter: brightness(0) saturate(100%) invert(82%) sepia(5%) saturate(846%) hue-rotate(320deg) brightness(110%) contrast(91%); @lavender-filter: brightness(0) saturate(100%) invert(81%) sepia(15%) saturate(429%) hue-rotate(314deg) brightness(103%) contrast(88%); @text-filter: brightness(0) saturate(100%) invert(83%) sepia(18%) saturate(893%) hue-rotate(285deg) brightness(104%) contrast(92%); @subtext1-filter: brightness(0) saturate(100%) invert(79%) sepia(18%) saturate(6315%) hue-rotate(206deg) brightness(102%) contrast(93%); @subtext0-filter: brightness(0) saturate(100%) invert(59%) sepia(37%) saturate(558%) hue-rotate(302deg) brightness(102%) contrast(86%); @overlay2-filter: brightness(0) saturate(100%) invert(56%) sepia(10%) saturate(1647%) hue-rotate(306deg) brightness(124%) contrast(87%); @overlay1-filter: brightness(0) saturate(100%) invert(66%) sepia(64%) saturate(291%) hue-rotate(335deg) brightness(97%) contrast(97%); @overlay0-filter: brightness(0) saturate(100%) invert(79%) sepia(61%) saturate(239%) hue-rotate(344deg) brightness(104%) contrast(87%); @surface2-filter: brightness(0) saturate(100%) invert(93%) sepia(12%) saturate(1081%) hue-rotate(47deg) brightness(88%) contrast(93%); @surface1-filter: brightness(0) saturate(100%) invert(92%) sepia(13%) saturate(865%) hue-rotate(110deg) brightness(86%) contrast(94%); @surface0-filter: brightness(0) saturate(100%) invert(81%) sepia(40%) saturate(308%) hue-rotate(142deg) brightness(93%) contrast(90%); @base-filter: brightness(0) saturate(100%) invert(68%) sepia(80%) saturate(206%) hue-rotate(156deg) brightness(91%) contrast(96%); @mantle-filter: brightness(0) saturate(100%) invert(66%) sepia(22%) saturate(823%) hue-rotate(183deg) brightness(99%) contrast(93%); @crust-filter: brightness(0) saturate(100%) invert(69%) sepia(54%) saturate(215%) hue-rotate(197deg) brightness(99%) contrast(96%); };
  @mocha-filters      { @rosewater-filter: brightness(0) saturate(100%) invert(88%) sepia(9%) saturate(344%) hue-rotate(320deg) brightness(104%) contrast(92%); @flamingo-filter: brightness(0) saturate(100%) invert(81%) sepia(22%) saturate(237%) hue-rotate(315deg) brightness(103%) contrast(90%); @pink-filter: brightness(0) saturate(100%) invert(72%) sepia(33%) saturate(282%) hue-rotate(274deg) brightness(110%) contrast(92%); @mauve-filter: brightness(0) saturate(100%) invert(60%) sepia(78%) saturate(229%) hue-rotate(222deg) brightness(104%) contrast(94%); @red-filter: brightness(0) saturate(100%) invert(80%) sepia(22%) saturate(4758%) hue-rotate(297deg) brightness(106%) contrast(91%); @maroon-filter: brightness(0) saturate(100%) invert(66%) sepia(16%) saturate(753%) hue-rotate(301deg) brightness(105%) contrast(89%); @peach-filter: brightness(0) saturate(100%) invert(69%) sepia(35%) saturate(468%) hue-rotate(337deg) brightness(103%) contrast(96%); @yellow-filter: brightness(0) saturate(100%) invert(95%) sepia(8%) saturate(1487%) hue-rotate(333deg) brightness(99%) contrast(97%); @green-filter: brightness(0) saturate(100%) invert(87%) sepia(7%) saturate(1716%) hue-rotate(65deg) brightness(105%) contrast(78%); @teal-filter: brightness(0) saturate(100%) invert(93%) sepia(6%) saturate(1903%) hue-rotate(108deg) brightness(92%) contrast(92%); @sky-filter: brightness(0) saturate(100%) invert(82%) sepia(11%) saturate(1349%) hue-rotate(151deg) brightness(103%) contrast(84%); @sapphire-filter: brightness(0) saturate(100%) invert(78%) sepia(6%) saturate(3997%) hue-rotate(167deg) brightness(96%) contrast(92%); @blue-filter: brightness(0) saturate(100%) invert(67%) sepia(10%) saturate(1764%) hue-rotate(181deg) brightness(102%) contrast(96%); @lavender-filter: brightness(0) saturate(100%) invert(73%) sepia(10%) saturate(1854%) hue-rotate(197deg) brightness(103%) contrast(99%); @text-filter: brightness(0) saturate(100%) invert(85%) sepia(13%) saturate(413%) hue-rotate(190deg) brightness(99%) contrast(94%); @subtext1-filter: brightness(0) saturate(100%) invert(84%) sepia(17%) saturate(460%) hue-rotate(193deg) brightness(93%) contrast(85%); @subtext0-filter: brightness(0) saturate(100%) invert(74%) sepia(9%) saturate(598%) hue-rotate(190deg) brightness(91%) contrast(93%); @overlay2-filter: brightness(0) saturate(100%) invert(71%) sepia(8%) saturate(762%) hue-rotate(191deg) brightness(85%) contrast(89%); @overlay1-filter: brightness(0) saturate(100%) invert(53%) sepia(13%) saturate(495%) hue-rotate(192deg) brightness(95%) contrast(94%); @overlay0-filter: brightness(0) saturate(100%) invert(43%) sepia(4%) saturate(2204%) hue-rotate(194deg) brightness(98%) contrast(78%); @surface2-filter: brightness(0) saturate(100%) invert(36%) sepia(10%) saturate(1054%) hue-rotate(195deg) brightness(90%) contrast(80%); @surface1-filter: brightness(0) saturate(100%) invert(24%) sepia(8%) saturate(1436%) hue-rotate(197deg) brightness(98%) contrast(85%); @surface0-filter: brightness(0) saturate(100%) invert(11%) sepia(4%) saturate(5718%) hue-rotate(199deg) brightness(98%) contrast(77%); @base-filter: brightness(0) saturate(100%) invert(7%) sepia(5%) saturate(6455%) hue-rotate(202deg) brightness(94%) contrast(87%); @mantle-filter: brightness(0) saturate(100%) invert(5%) sepia(5%) saturate(6679%) hue-rotate(202deg) brightness(95%) contrast(89%); @crust-filter: brightness(0) saturate(100%) invert(4%) sepia(4%) saturate(7225%) hue-rotate(202deg) brightness(96%) contrast(93%); };
}
```
