### ISSUE TITLE
unclear tip

### ISSUE THREAD

**Issue by sineptic** [catppuccin/userstyles#1141]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

[`How do I theme images and SVGs?`](https://github.com/catppuccin/userstyles/blob/main/docs/tips-and-tricks.md#svg-background-images) don't clarify, that it don't work if you don't add any generic in svg, but almost all(I think) do this as first step.

**Comment by uncenter** [comment]
>  it don't work if you don't add any generic in svg

Please clarify, I don't know what you mean by this.

**Comment by sineptic** [comment]
don't work: 
``` less
.some {
  @svg: escape('<svg fill="blue" width="300" height="130" xmlns="http://www.w3.org/2000/svg"><rect width="200" height="100" x="10" y="10" rx="20" ry="20"/></svg>');
  background-image: url("data:image/svg+xml,@{svg}");
}
```
work: 
``` less
.some {
  @svg: escape('<svg fill="@{mauve}" width="300" height="130" xmlns="http://www.w3.org/2000/svg"><rect width="200" height="100" x="10" y="10" rx="20" ry="20"/></svg>');
  background-image: url("data:image/svg+xml,@{svg}");
}
```
