### ISSUE TITLE
Missing styles in game analysis and studies

### ISSUE THREAD

**Issue by SebasF1349** [catppuccin/userstyles#1636]
### Is there an existing issue outlining your problem?

- [x] I am using the latest version of the provided userstyle.
- [x] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:lichess

### Describe your problem.

As can be seen in the first two screenshots below, some pages in lichess.org are missing styles.

### Original colors
![Image](https://github.com/user-attachments/assets/8bc543e6-e396-406b-9cae-e1cad80856b1)
![Image](https://github.com/user-attachments/assets/8055ea4f-2703-4187-9f06-185aab5cff3b)

### My own modification
![Image](https://github.com/user-attachments/assets/afc4e87b-590d-4a41-8eb4-70f987692cb3)
![Image](https://github.com/user-attachments/assets/c63d03e0-0d88-4ab2-bc7c-82c4bf5959f1)

### What browser(s) are you seeing the problem on?

Vivaldi 7.1.3570.54 (Chrome/132.0.0.0)

### Any additional comments?

I've made my own modifications to improve the coloring (can be seen in the last two screenshot above), but I have only tested it in my own browser and with the mocha flavour. I also didn't modify any of the existing styles and didn't check other pages I don't usually use, so there are surely some improvements to be made. But I hope this snippet can help to improve the existing amazing theme.

```css
    /* Main */ 
    header.scrolled {
      background: @crust !important;
    }
      
    /* Notation */ 
    .result,
    .status {
      background: @crust !important;
    }
    line move {
      color: @subtext0 !important;
    }
    interrupt {
      background: @crust !important;
    }
    
    /* Analysis */
    .palantir {
      color: @blue !important;
    }
    span[role="tab"] {
      color: @blue !important;
    }
    povs:not(.printable) {
      background: @crust !important;
    }

    div[class^='advice-summary']:not(.symbol) {
      color: @subtext1 !important;
    }
    
    /* Study */
    .study__player {
      background: @crust !important;
    }
    .study__chapters {
        background: @crust !important;
    }
    button.next {
      background: @surface2 !important;
      color: @subtext0 !important;
    }
    .study__metadata,
    .study__metadata h2,
    .slist tbody tr:nth-child(even),
    .slist tbody tr:nth-child(even) input {
      background: @crust;
    }
    .slist tbody tr:nth-child(odd),
    .slist tbody tr:nth-child(odd) input {
      background: @surface0;
    }
    .slist tbody th {
      color: @subtext0 !important;      
    }
    .study__comment,
    .study__message,
    .study__multiboard,
    .study__share,
    .gamebook .comment,
    .gamebook .comment::after {
      background: @surface0;
    }
```
