### ISSUE TITLE
Fix for sidebar question and article links

### ISSUE THREAD

**Issue by SturgeonInc** [catppuccin/userstyles#1671]
### Is there an existing issue outlining your problem?

- [x] I am using the latest version of the provided userstyle.
- [x] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:stack-overflow

### Describe your problem.

On Stack Overflow and AskUbuntu this text renders as black, making it hard to read and ugly

This fixes it:
```css
.s-link 
{
  color: @text;
}

.js-gps-track.question-hyperlink.mb0 {
  color: @subtext0;
}
```

### Attach screenshots.

![Image](https://github.com/user-attachments/assets/198a0bf3-c4a1-436b-8725-be899b1e6a54)

![Image](https://github.com/user-attachments/assets/e1b6befd-f78b-4993-b6b5-a20f08196d0d)

### What browser(s) are you seeing the problem on?

Firefox 136.0.2-1
