### ISSUE TITLE
Nix Wiki colors mismatch,

### ISSUE THREAD

**Issue by anasgets111** [catppuccin/userstyles#1728]
### Is there an existing issue outlining your problem?

- [x] I am using the latest version of the provided userstyle.
- [x] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:wiki.nixos.org

### Describe your problem.

some boxes are colored in bright colors with white text making it impossible to read, attached a screenshot from [installation page](https://wiki.nixos.org/wiki/NixOS_Installation_Guide)

### Attach screenshots.

![Image](https://github.com/user-attachments/assets/b56cae9d-fb0c-47f6-9bf6-c640fc8b2d82) 

### What browser(s) are you seeing the problem on?

1.11.5b (Firefox 137.0.2)

**Comment by frahz** [comment]
You can add this to your styles as  a work around:
```css
.mw-content-ltr div[style="padding: 0.5em; margin: 0.50em 0; background-color: var(--background-color-content-added); border: thin solid var(--border-color-progressive); overflow: hidden;"] {
  color: @base;
}
```
