### ISSUE TITLE
Adding new userstyle for a potentially sensitive information page?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [catppuccin/userstyles#189]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

Hi,
I have created a new userstyle for BoringProxy (https://boringproxy.io/) which is a self hosted networking solution and provides a web dashboard when deployed.

I have tested the userstyle and it works well. My issue is with creating the image to show the userstyle in action, as it contains potentially sensitive information of domain names and IP addresses. To even create a dummy instance would require a domain name, which I do not have to spare.

**Comment by nekowinston** [comment]
You could use this snippet to swap out the font for Flow Circular, a redacted font:
```css
@import url('https://fonts.googleapis.com/css2?family=Flow+Circular&display=swap');

* {
  font-family: 'Flow Circular', cursive;
}
```

Example with your issue:
![2023-09-05-143710@2x](https://github.com/catppuccin/userstyles/assets/79978224/99ffbb94-8b80-4eed-99bf-925e6196a2e8)

Of course it would look even better if you just reduced this style to elements with sensitive info. 🙂
