### ISSUE TITLE
Missing Colors in Google Mobile Version 

### ISSUE THREAD

**Issue by LBO44** [catppuccin/userstyles#365]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:google

### Describe your problem.

Google userstyle is not fully completed for the mobile version of Google, a lot of elements have the default color.

### Attach screenshots.

![Screenshot_2023-12-02-14-38-18-392_com kiwibrowser browser-edit](https://github.com/catppuccin/userstyles/assets/146635915/aec7df57-b89a-45b2-9c68-d53b27bffa7b)
![Screenshot_2023-12-02-14-37-52-674_com kiwibrowser browser-edit](https://github.com/catppuccin/userstyles/assets/146635915/1f6fda55-5a1d-4e8d-95b3-da4e99f7c161)

### What browser(s) are you seeing the problem on?

Kiwi Browser 120.0.X

**Comment by WmeLuna** [comment]
And on desktop, here is a few with fixes for each

### Search Header
![image](https://github.com/catppuccin/userstyles/assets/46545277/0bc1f353-0291-4a06-b520-268b42286def)
```css
.rfiSsc {
 padding-top: revert;
 background: revert;
}
```
### Some search results
![image](https://github.com/catppuccin/userstyles/assets/46545277/0f2ebf88-9e99-4891-a502-08dc79c0e206)
```css
g-inner-card {
 background-color:revert;
}
```

Pinned Search form (when you scroll down)
![image](https://github.com/catppuccin/userstyles/assets/46545277/3f738fa8-53f5-4dbc-ac16-d1d32812485e)
```css
#searchform {
 background: /*idk what color would be good for this */
}
```

### X more images
![image](https://github.com/catppuccin/userstyles/assets/46545277/a40d9761-27bb-4896-b0c0-565a98e7a80f)
```css
/* copied from "More results" button */
.ZFiwCf{
 background: #313244;
}
.Bi9oQd {
 background-color: #585b70;
}
```

### All filters
![image](https://github.com/catppuccin/userstyles/assets/46545277/58e54cc3-5961-4189-bf25-4a0c152f58e6)
```css
/* this is existing userstyle code just with !important added*/
body .fKmH1e:hover {
    background-color: #313244 !important;
    border-color: #45475a;
}
```
