### ISSUE TITLE
Syntax highlighting colors for Wikipedia.

### ISSUE THREAD

**Issue by aspizu** [catppuccin/userstyles#601]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:wikipedia

### Describe your problem.

Syntax highlighting colors for Wikipedia.

### Attach screenshots.

Need to add css something like:

```css
.mw-highlight .nf {
    color: #89b4fa;
}

.mw-highlight .kt {
    color: #f38ba8;
}

.mw-highlight .c1, .mw-highlight .cm {
    color: #6c7086;
}

.mw-highlight .mi {
    color: #74c7ec;
}

.mw-highlight .k {
    color: #a6e3a1;
}

.mw-highlight .nb {
    color: #94e2d5;
}

.mw-highlight .mf, .mw-highlight .mh, .mw-highlight .mb {
    color: #9399b2;
}

.mw-highlight .cp {
    color: #fab387;
}

.mw-highlight .cpf {
    color: #eba0ac;
}

.mw-highlight .s {
    color: #f9e2af;
}

.mw-highlight .se {
    color: #fab387;
}
```

### What browser(s) are you seeing the problem on?

Firefox v112.0.2
