### ISSUE TITLE
GitHub: large sections unthemed

### ISSUE THREAD

**Issue by enderprism** [catppuccin/userstyles#689]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

A lot of stuff on GitHub has suddenly stopped being themed.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/76617157/fb110224-1d46-4e31-9cd9-a3154aaf558a)

### What browser(s) are you seeing the problem on?

Firefox v124.0

**Comment by uncenter** [comment]
Thanks for making this issue! I just noticed it about 10 minutes ago when I reloaded, it appears they have released a whole new underlying UI (different CSS strategy, very different and better looking HTML). Many things have changed, for now I advise you simply disable the userstyle xD.

**Comment by FireIsGood** [comment]
Just opened GitHub and saw this. Hope the maintainers can find the time to update!

For anyone looking here who just wants a patch fix of the basics until we get a full update, here's a userstyle:

<details>

<summary>CSS code block of a userstyle</summary>

```css
/* ==UserStyle==
@name           GitHub Patch Catppuccin
@namespace      github.com/openstyles/stylus
@version        0.1.0
@description    A temporary patch to GitHub, remove this when we get an update!
@author         FireIsGood
==/UserStyle== */
@-moz-document domain("github.com") {
  [data-color-mode="dark"][data-dark-theme="dark"] {
    /* Color accents */
    --color-accent-fg: var(--sapphire);
    --color-open-emphasis: var(--green);

    --bgColor-default: var(--base);
    --bgColor-muted: var(--mantle);
    --overlay-bgColor: var(--base);
    --bgColor-inset: var(--base);

    /* The colorful buttons */
    --color-btn-primary-bg: var(--green);

    /* The grey buttons */
    --color-btn-bg: var(--surface0);
    --color-btn-border: var(--surface0);
    --color-btn-hover-bg: var(--surface1);
    --color-btn-hover-border: var(--surface1);

    /* Misc accent items */
    --underlineNav-borderColor-active: var(--sapphire);
  }

  /* Colors (currently Macchiato)
     go to https://unpkg.com/@catppuccin/palette@1.1.0/css/catppuccin.css
     and then cut off namespace from the variables for your theme
  */
  :root {
    --rosewater: #f4dbd6;
    --flamingo: #f0c6c6;
    --pink: #f5bde6;
    --mauve: #c6a0f6;
    --red: #ed8796;
    --maroon: #ee99a0;
    --peach: #f5a97f;
    --yellow: #eed49f;
    --green: #a6da95;
    --teal: #8bd5ca;
    --sky: #91d7e3;
    --sapphire: #7dc4e4;
    --blue: #8aadf4;
    --lavender: #b7bdf8;
    --text: #cad3f5;
    --subtext1: #b8c0e0;
    --subtext0: #a5adcb;
    --overlay2: #939ab7;
    --overlay1: #8087a2;
    --overlay0: #6e738d;
    --surface2: #5b6078;
    --surface1: #494d64;
    --surface0: #363a4f;
    --base: #24273a;
    --mantle: #1e2030;
    --crust: #181926;
  }
}
```

</details>
