### ISSUE TITLE
Set ::selection consistently across userstyles

### ISSUE THREAD

**Issue by uncenter** [catppuccin/userstyles#765]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

We have quite a few variations of theming `::selection`  in this repository (see https://github.com/search?q=repo:catppuccin/userstyles+::selection&type=code). Ideally we could standardize it across userstyles, and maybe even add it as boilerplate to the template.

I've found through trial and error that the following looks the best in the most scenarios:
```css
::selection {
  background-color: fade(@accent-color, 20%);
}
```

Though I am open to suggestions :)

**Comment by isabelroses** [comment]
I like the idea that you came to since that was the one I was originally for too. But the biggest issue was on some backgrounds it would look particularly odd, or make the text harder to read. So I recently started moving to 

```less
::selection {
  color: @base;
  background-color: @accent-color;
}
```

But i would hardly say that this is the best outcome either because on the highlight would not be seen at all on something like YouTube's subscribe button.

Ideally we would apply a fade, mix or both to the background color whilst setting an appropriate text color too.
