### ISSUE TITLE
GitHub: the header is strictly following the light flavor colors when logged out

### ISSUE THREAD

**Issue by thismoon** [catppuccin/userstyles#954]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

when browsing github while logged out, the colors of the header are strictly being used from the light flavor.
i made a work around that forces using the dark flavor (it will force a dark header while using the light flavor). here's the work around (replace lines 195 to 200 with this):
```css
    --header-fgColor-default: @catppuccin[@@darkFlavor][@text];
    --header-fgColor-logo: @catppuccin[@@darkFlavor][@text];
    --header-bgColor: @catppuccin[@@darkFlavor][@crust];
    --header-borderColor-divider: #8b949e;
    --headerSearch-bgColor: @catppuccin[@@darkFlavor][@mantle];
    --headerSearch-borderColor: @catppuccin[@@darkFlavor][@surface0];
      .header-logged-out{color:@catppuccin[@@darkFlavor][@text]};
```
this work around doesn't fix everything. some text is still being styled with the light flavor colors therefore being not easily readable
this issue isn't present when logged in.
also without the catppuccin theme, github uses a dark header by default even when the theme is light

### Attach screenshots.

the current userstyle:
![image](https://github.com/catppuccin/userstyles/assets/107642606/19666463-e060-47e5-9b6a-46a03db93655)
the work around:
![image](https://github.com/catppuccin/userstyles/assets/107642606/76ba67d6-2b84-4eae-ab4b-aa6f00a65ba8)
the work around with light mode:
![image](https://github.com/catppuccin/userstyles/assets/107642606/1681571e-84f7-4b17-b76d-773225781b62)
default github (no theme) with light mode:
![image](https://github.com/catppuccin/userstyles/assets/107642606/33f4e556-d067-41b5-89af-6a086173c6dd)

### What browser(s) are you seeing the problem on?

Firefox v126.0.1
